[project]
authors = ["ivo <45843343+ivomofor@users.noreply.github.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "workingProject"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = "~=24.5"
